"""Code execution models for Docker sandbox."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class CodeBlock(BaseModel):
    """Code generated by an agent for sandboxed execution."""

    language: Literal["python", "R"]
    code: str
    dependencies: list[str] = []
    expected_output: str = ""  # Pydantic model class name
    estimated_runtime: str = ""
    execution_target: Literal["local", "hpc"] = "local"


class ExecutionResult(BaseModel):
    """Result from code sandbox execution."""

    stdout: str = ""
    stderr: str = ""
    files_created: list[str] = []
    runtime_seconds: float = 0.0
    exit_code: int = 0
