"""Story frame models for W11 narrative planning workflow.

Supports the iterative story planning process where researchers choose
the best narrative angle for their paper before writing (W4).

NarrativeType: 6 distinct frame archetypes.
StoryFrame: One candidate narrative arc with hook, claim, and evidence mapping.
StoryFrameSet: Collection of 3-5 ranked alternatives generated by W11.
NarrativeDriftReport: Result of W4 narrative consistency check per section.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class NarrativeType(str, Enum):
    """Archetype of the scientific narrative arc."""

    mechanism_discovery = "mechanism_discovery"  # "we find the switch that causes X"
    paradigm_challenge = "paradigm_challenge"  # "gene X, assumed Y, actually does Z"
    clinical_implication = "clinical_implication"  # "targeting X prevents Y in patients"
    field_bridge = "field_bridge"  # "spaceflight mirrors aging — unified framework"
    negative_reframe = "negative_reframe"  # "X does not work, but reveals Y"
    method_breakthrough = "method_breakthrough"  # "our approach finally measures X"


class StoryFrame(BaseModel):
    """One candidate narrative arc for a manuscript.

    Generated by W11, selected by the researcher, then propagated
    through W4 writing steps as a guiding anchor.
    """

    frame_id: str  # e.g. "SF-001"
    narrative_type: NarrativeType
    hook: str  # Opening sentence that would grab a Nature/NEJM editor
    central_tension: str  # Expected vs. found — the core scientific conflict
    core_claim: str  # One-sentence contribution statement
    supporting_findings: list[str]  # Data points that support this framing
    figure_sequence: list[str]  # Suggested figure order to tell this story
    target_tier: str  # "nature_cell" | "specialty" | "grant"
    novelty_rationale: str  # Why this angle is novel vs. prior literature
    blind_spots: list[str]  # What this framing intentionally leaves out
    impact_score: float = Field(ge=0.0, le=1.0)  # 0=incremental, 1=paradigm-shifting
    version: int = Field(default=1)  # Increments on each user-approved update
    provenance: Literal["llm", "synthetic_fallback"] = "llm"


class StoryFrameSet(BaseModel):
    """Collection of 3-5 alternative narrative frames, ranked by impact.

    Generated in W11 GENERATE_FRAMES step via single Opus call.
    Stored in instance.session_manifest["frame_options"] at HUMAN_CHECKPOINT.
    After user selection, selected frame stored as ["selected_story_frame"].
    """

    frames: list[StoryFrame]  # 3-5 alternatives, pre-ranked by impact_score
    selected_frame_id: str | None = None  # Set after HC selection
    generation_context: str = ""  # Summary of research data used for generation
    generation_mode: Literal["llm", "synthetic_fallback"] = "llm"
    fallback_reason: str | None = None


class NarrativeDriftReport(BaseModel):
    """Result of a narrative consistency check in W4.

    Produced by NarrativeConsistencyChecker (Haiku) after DRAFT and REVISION.
    Stored in instance.session_manifest and broadcast via SSE if score < 0.75.
    Never causes a workflow pause — SSE warning only.
    """

    section_id: str  # e.g. "DRAFT" or "REVISION"
    consistency_score: float = Field(ge=0.0, le=1.0)  # 1.0 = perfectly aligned
    drift_summary: str | None = None  # What diverges (if score < 0.75)
    recommendation: str  # "on_track" | "minor_drift" | "major_drift"
    specific_divergences: list[str] = Field(default_factory=list)  # Sentence-level issues
