#!/usr/bin/env python3
"""Apply deterministic corpus curation actions from QA curation queue.

Default behavior (hard gate):
- Remove entries carrying structural/consistency hard flags
- Keep soft-review rows untouched

Outputs:
- curated corpus JSONL
- change log JSONL
- stats JSON
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

HARD_REMOVE_PREFIXES = (
    "invalid_type",
    "nongenuine_noncontextual",
    "genuine_marked_contextual",
    "missing_required_fields",
    "confidence_not_numeric",
    "confidence_out_of_range",
    "empty_claim",
    "truncated_pvalue_pattern",
    "claim_a_unmatched_closing_paren",
    "claim_b_unmatched_closing_paren",
    "claim_a_suspicious_fragment_prefix",
    "claim_b_suspicious_fragment_prefix",
    "duplicate_exact_pair",
)


def _flag_matches_prefix(flag: str, prefix: str) -> bool:
    return flag == prefix or flag.startswith(f"{prefix}:")


def _is_hard_flag(flag: str) -> bool:
    return any(_flag_matches_prefix(flag, prefix) for prefix in HARD_REMOVE_PREFIXES)


def parse_args() -> argparse.Namespace:
    base = Path(__file__).resolve().parent / "output" / "v3"
    parser = argparse.ArgumentParser(description="Apply deterministic curation queue actions.")
    parser.add_argument(
        "--input-corpus",
        type=Path,
        default=base / "corpus_final_v5_consistent.jsonl",
        help="Input corpus JSONL.",
    )
    parser.add_argument(
        "--curation-queue",
        type=Path,
        default=base / "qa_v5" / "corpus_curation_queue.jsonl",
        help="Curation queue JSONL generated by qa_corpus_v3.py.",
    )
    parser.add_argument(
        "--output-corpus",
        type=Path,
        default=base / "corpus_final_v6_curated.jsonl",
        help="Output curated corpus JSONL.",
    )
    parser.add_argument(
        "--changes-out",
        type=Path,
        default=base / "corpus_final_v6_curated_changes.jsonl",
        help="Change log JSONL.",
    )
    parser.add_argument(
        "--stats-out",
        type=Path,
        default=base / "corpus_final_v6_curated_stats.json",
        help="Summary stats JSON.",
    )
    return parser.parse_args()


def _load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def main() -> None:
    args = parse_args()
    rows = _load_jsonl(args.input_corpus)
    queue_rows = _load_jsonl(args.curation_queue)

    remove_by_id: dict[str, list[str]] = {}
    for row in queue_rows:
        rid = row.get("id", "")
        if not rid:
            continue
        hard_flags = [
            flag
            for flag in row.get("hard_flags", row.get("flags", []))
            if _is_hard_flag(flag)
        ]
        if hard_flags:
            remove_by_id[rid] = sorted(set(hard_flags))

    out_rows: list[dict] = []
    changes: list[dict] = []
    for row in rows:
        rid = row.get("id", "")
        if rid in remove_by_id:
            changes.append(
                {
                    "id": rid,
                    "action": "removed_hard_quality_flag",
                    "hard_flags": remove_by_id[rid],
                    "old_type": row.get("contradiction_type"),
                    "old_is_genuine": row.get("is_genuine_contradiction"),
                }
            )
            continue
        out_rows.append(row)

    args.output_corpus.parent.mkdir(parents=True, exist_ok=True)
    with args.output_corpus.open("w", encoding="utf-8") as fp:
        for row in out_rows:
            fp.write(json.dumps(row, ensure_ascii=False) + "\n")

    with args.changes_out.open("w", encoding="utf-8") as fp:
        for row in changes:
            fp.write(json.dumps(row, ensure_ascii=False) + "\n")

    removed_by_type = Counter(change["old_type"] for change in changes)
    removed_by_flag = Counter(flag for change in changes for flag in change.get("hard_flags", []))
    removed_genuine = sum(1 for change in changes if change["old_is_genuine"])
    stats = {
        "input_corpus": str(args.input_corpus),
        "curation_queue": str(args.curation_queue),
        "output_corpus": str(args.output_corpus),
        "total_input_rows": len(rows),
        "total_output_rows": len(out_rows),
        "removed_rows": len(changes),
        "removed_rows_genuine": removed_genuine,
        "removed_rows_contextual": len(changes) - removed_genuine,
        "removed_by_type": dict(removed_by_type),
        "removed_by_hard_flag": dict(removed_by_flag),
        "hard_remove_prefixes": list(HARD_REMOVE_PREFIXES),
    }
    args.stats_out.write_text(json.dumps(stats, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print("Curation queue applied")
    print(f"  input={len(rows)} output={len(out_rows)} removed={len(changes)}")
    print(f"  removed_genuine={removed_genuine} removed_contextual={len(changes) - removed_genuine}")
    print(f"  output={args.output_corpus}")
    print(f"  changes={args.changes_out}")
    print(f"  stats={args.stats_out}")


if __name__ == "__main__":
    main()
