"""W9 result exporter — TSV, HTML, JSON formats.

Converts W9BioinformaticsReport to researcher-friendly output formats.
Uses only Python stdlib (string.Template for HTML, csv for TSV).
"""

from __future__ import annotations

import csv
import io
import json
import logging
from datetime import datetime, timezone
from html import escape as _esc
from pathlib import Path
from string import Template

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# TSV Export
# ---------------------------------------------------------------------------


def export_degs_tsv(report: dict) -> str:
    """Export DEG list as TSV (gene, log2FC, padj, direction)."""
    output = io.StringIO()
    writer = csv.writer(output, delimiter="\t")
    writer.writerow(["gene", "log2FC", "padj", "direction"])

    expr = report.get("expression_analysis", {})
    for deg in expr.get("up_regulated", []):
        if isinstance(deg, dict):
            writer.writerow([
                deg.get("gene", ""),
                deg.get("log2FC", ""),
                deg.get("padj", ""),
                "up",
            ])
    for deg in expr.get("down_regulated", []):
        if isinstance(deg, dict):
            writer.writerow([
                deg.get("gene", ""),
                deg.get("log2FC", ""),
                deg.get("padj", ""),
                "down",
            ])

    return output.getvalue()


def export_variants_tsv(report: dict) -> str:
    """Export variant annotations as TSV."""
    output = io.StringIO()
    writer = csv.writer(output, delimiter="\t")
    writer.writerow(["gene", "variant_type", "consequence", "significance"])

    variant = report.get("variant_annotation", {})
    for v in variant.get("high_impact_variants", []):
        if isinstance(v, dict):
            writer.writerow([
                v.get("gene", ""),
                v.get("type", ""),
                v.get("consequence", ""),
                v.get("significance", ""),
            ])

    return output.getvalue()


def export_pathways_tsv(report: dict) -> str:
    """Export pathway enrichment as TSV."""
    output = io.StringIO()
    writer = csv.writer(output, delimiter="\t")
    writer.writerow(["source", "term", "pvalue", "gene_ratio", "genes"])

    pathway = report.get("pathway_enrichment", {})
    for p in pathway.get("top_pathways", []):
        if isinstance(p, dict):
            genes = p.get("genes", [])
            gene_str = ",".join(genes) if isinstance(genes, list) else str(genes)
            writer.writerow([
                p.get("source", ""),
                p.get("name", ""),
                p.get("pvalue", ""),
                p.get("gene_ratio", ""),
                gene_str,
            ])

    return output.getvalue()


# ---------------------------------------------------------------------------
# HTML Export
# ---------------------------------------------------------------------------


_HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>W9 Bioinformatics Report — $query</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }
  h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 10px; }
  h2 { color: #16213e; margin-top: 30px; }
  .meta { color: #666; font-size: 0.9em; }
  .summary-box { background: #f0f4f8; border-left: 4px solid #0f3460; padding: 15px; margin: 15px 0; }
  .finding { background: #fafafa; border: 1px solid #e0e0e0; padding: 10px; margin: 8px 0; border-radius: 4px; }
  .finding-up { border-left: 3px solid #e74c3c; }
  .finding-down { border-left: 3px solid #3498db; }
  table { border-collapse: collapse; width: 100%; margin: 15px 0; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background: #f5f5f5; }
  .warning { color: #e67e22; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 0.8em; }
</style>
</head>
<body>
<h1>W9 Deep Bioinformatics Analysis</h1>
<p class="meta">
  <strong>Query:</strong> $query<br>
  <strong>Workflow ID:</strong> $workflow_id<br>
  <strong>Generated:</strong> $generated_at<br>
  <strong>Cost:</strong> $$$total_cost
</p>

<div class="summary-box">
<h2>Executive Summary</h2>
<p>$executive_summary</p>
</div>

$key_findings_html

$expression_html

$pathway_html

$variant_html

$limitations_html

<div class="footer">
  Generated by BioTeam-AI W9 Pipeline. All findings require experimental validation.
</div>
</body>
</html>""")


def _build_key_findings_html(findings: list) -> str:
    if not findings:
        return ""
    items = "".join(f"<li>{_esc(str(f))}</li>" for f in findings)
    return f"<h2>Key Findings</h2><ul>{items}</ul>"


def _build_expression_html(expr: dict) -> str:
    if not expr or (not expr.get("up_regulated") and not expr.get("down_regulated")):
        return ""

    rows = ""
    for deg in (expr.get("up_regulated", []) + expr.get("down_regulated", []))[:20]:
        if isinstance(deg, dict):
            direction = "up" if deg.get("log2FC", 0) > 0 else "down"
            rows += f"<tr><td>{_esc(str(deg.get('gene', '')))}</td><td>{_esc(str(deg.get('log2FC', '')))}</td>"
            rows += f"<td>{_esc(str(deg.get('padj', '')))}</td><td>{direction}</td></tr>"

    return f"""<h2>Expression Analysis</h2>
<p>Total DEGs: {_esc(str(expr.get('total_degs', 'N/A')))} | {_esc(str(expr.get('comparison', '')))}</p>
<table><tr><th>Gene</th><th>log2FC</th><th>padj</th><th>Direction</th></tr>
{rows}
</table>"""


def _build_pathway_html(pathway: dict) -> str:
    if not pathway or not pathway.get("top_pathways"):
        return ""

    rows = ""
    for p in pathway.get("top_pathways", [])[:15]:
        if isinstance(p, dict):
            rows += f"<tr><td>{_esc(str(p.get('source', '')))}</td><td>{_esc(str(p.get('name', '')))}</td>"
            rows += f"<td>{_esc(str(p.get('pvalue', '')))}</td></tr>"

    return f"""<h2>Pathway Enrichment</h2>
<p>Significant terms: {_esc(str(pathway.get('significant_terms', 'N/A')))}</p>
<table><tr><th>Source</th><th>Term</th><th>P-value</th></tr>
{rows}
</table>"""


def _build_variant_html(variant: dict) -> str:
    if not variant or not variant.get("high_impact_variants"):
        return ""

    rows = ""
    for v in variant.get("high_impact_variants", [])[:20]:
        if isinstance(v, dict):
            rows += f"<tr><td>{_esc(str(v.get('gene', '')))}</td><td>{_esc(str(v.get('consequence', '')))}</td>"
            rows += f"<td>{_esc(str(v.get('significance', '')))}</td></tr>"

    return f"""<h2>Variant Annotation</h2>
<p>Total variants: {_esc(str(variant.get('total_variants', 'N/A')))} | High impact: {len(variant.get('high_impact_variants', []))}</p>
<table><tr><th>Gene</th><th>Consequence</th><th>Significance</th></tr>
{rows}
</table>"""


def _build_limitations_html(limitations: list) -> str:
    if not limitations:
        return ""
    items = "".join(f"<li>{_esc(str(lim))}</li>" for lim in limitations)
    return f"<h2>Limitations</h2><ul class='warning'>{items}</ul>"


def export_html(report: dict) -> str:
    """Generate a self-contained HTML report from W9 results."""
    return _HTML_TEMPLATE.safe_substitute(
        query=_esc(str(report.get("query", "N/A"))),
        workflow_id=_esc(str(report.get("workflow_id", "N/A"))),
        generated_at=_esc(str(report.get("generated_at", datetime.now(timezone.utc).isoformat()))),
        total_cost=f"{report.get('total_cost_usd', 0):.2f}",
        executive_summary=_esc(str(report.get("executive_summary", "No summary available."))),
        key_findings_html=_build_key_findings_html(report.get("key_findings", [])),
        expression_html=_build_expression_html(report.get("expression_analysis", {})),
        pathway_html=_build_pathway_html(report.get("pathway_enrichment", {})),
        variant_html=_build_variant_html(report.get("variant_annotation", {})),
        limitations_html=_build_limitations_html(report.get("limitations", [])),
    )


# ---------------------------------------------------------------------------
# JSON Export (passthrough with formatting)
# ---------------------------------------------------------------------------


def export_json(report: dict) -> str:
    """Export report as formatted JSON."""
    return json.dumps(report, indent=2, default=str, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Unified export function
# ---------------------------------------------------------------------------


def export_w9_report(report: dict, output_dir: str, formats: list[str] | None = None) -> dict[str, str]:
    """Export W9 report to multiple formats.

    Args:
        report: W9BioinformaticsReport as dict.
        output_dir: Directory to write files.
        formats: List of formats to export. Default: ["tsv", "html", "json"].

    Returns:
        Dict mapping format → file path.
    """
    if formats is None:
        formats = ["tsv", "html", "json"]

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    exported: dict[str, str] = {}

    if "tsv" in formats:
        # Write DEGs
        degs_path = out_path / "degs.tsv"
        degs_path.write_text(export_degs_tsv(report))
        exported["degs_tsv"] = str(degs_path)

        # Write variants
        variants_path = out_path / "variants.tsv"
        variants_path.write_text(export_variants_tsv(report))
        exported["variants_tsv"] = str(variants_path)

        # Write pathways
        pathways_path = out_path / "pathways.tsv"
        pathways_path.write_text(export_pathways_tsv(report))
        exported["pathways_tsv"] = str(pathways_path)

    if "html" in formats:
        html_path = out_path / "report.html"
        html_path.write_text(export_html(report))
        exported["html"] = str(html_path)

    if "json" in formats:
        json_path = out_path / "report.json"
        json_path.write_text(export_json(report))
        exported["json"] = str(json_path)

    logger.info("Exported W9 report to %s: %s", output_dir, list(exported.keys()))
    return exported
