"""initial_baseline_16_tables

Revision ID: 037b71f6d488
Revises:
Create Date: 2026-02-25 00:15:00.287874

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '037b71f6d488'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_turn',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routed_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_turn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turn_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('topic_profile',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queries', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digest_entry',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'external_id', name='uq_digest_entry_topic_external')
    )
    with op.batch_alter_table('digest_entry', schema=None) as batch_op:
        batch_op.create_index('ix_digest_entry_fetched_at', ['fetched_at'], unique=False)
        batch_op.create_index('ix_digest_entry_relevance', ['relevance_score'], unique=False)
        batch_op.create_index('ix_digest_entry_source', ['source'], unique=False)
        batch_op.create_index('ix_digest_entry_topic_id', ['topic_id'], unique=False)

    op.create_table('digest_report',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('source_breakdown', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_report', schema=None) as batch_op:
        batch_op.create_index('ix_digest_report_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_digest_report_topic_id', ['topic_id'], unique=False)

    with op.batch_alter_table('workflow_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_manifest', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('citation_report', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rcmxt_scores', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_instance', schema=None) as batch_op:
        batch_op.drop_column('rcmxt_scores')
        batch_op.drop_column('citation_report')
        batch_op.drop_column('session_manifest')

    with op.batch_alter_table('digest_report', schema=None) as batch_op:
        batch_op.drop_index('ix_digest_report_topic_id')
        batch_op.drop_index('ix_digest_report_created_at')

    op.drop_table('digest_report')
    with op.batch_alter_table('digest_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_digest_entry_topic_id')
        batch_op.drop_index('ix_digest_entry_source')
        batch_op.drop_index('ix_digest_entry_relevance')
        batch_op.drop_index('ix_digest_entry_fetched_at')

    op.drop_table('digest_entry')
    op.drop_table('topic_profile')
    with op.batch_alter_table('conversation_turn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turn_conversation_id'))

    op.drop_table('conversation_turn')
    op.drop_table('conversation')
    # ### end Alembic commands ###
